version: '3'

services:

  mysql:
    image: mysql:5.7
    restart: always
    command:
        --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DIR}:/var/lib/data
      - ${MYSQL_DIR}/db_lottery.sql:/etc/mysql/db_lottery.sql
    ports:
      - 3306:3306 #外:内

  redis:
    image: redis:4
    restart: always
    volumes:
      - "${REDIS_DIR}/data:/data"
    ports:
      - 6379:6379 #外:内

  api_service:
    image: registry.cn-shanghai.aliyuncs.com/eilingeloveduzi/eilinge:latest
    restart: always
    environment:
      MYSQL_DSN: "root:eilinge@tcp(172.19.37.39:3306)/lottery?charset=utf-8"
      REDIS_ADDR: "172.19.37.39:6379"
      REDIS_DB: "0"
      SESSION_SECRE: "3Ztqcc74gu27eUz"
    ports:
      - 8000:8000 #外:内
    depends_on:
      - mysql
      - redis
