version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql/data
    ports:
      - 3306:3306 #外:内