version: "3"

services:
  api:
    image:
    restart: always
    environment:
      MYSQL_DSN: "root:eilinge@tcp(172.19.37.39:3306)/lottery?charset=utf-8"
      REDIS_ADDR: "172.19.37.39:6379"
      REDIS_DB: "0"
      SESSION_SECRE: "3Ztqcc74gu27eUz"
    ports:
      - 8080:8080 #外:内